# Generated by Django 3.2.3 on 2021-05-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(default='', max_length=100)),
                ('final', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
